### ISSUE TITLE
Microbit Package

### ISSUE THREAD

**Issue by maddie4832** [ADataDate/pxt-airQuality#2]
The link to the package does not work. Is there an updated link to open the package in MakeCode?

**Comment by ADataDate** [comment]
This package has not been approved by Microsoft yet.  The best you can do currently is create the custom blocks locally. 

In order to add custom.ts to your project,

go to JavaScript,
click on the Explorer view and expand it
click on the + button that just appeared
accept the dialog to add a custom.ts file in your project.
Copy and paste the Javscript code provided in this repo into custom.ts 
and now it should show up in your editor.

**Comment by ADataDate** [comment]
I mean to copy and paste airQuality.ts into custom.ts

**Comment by ADataDate** [comment]
You will also need to delete everything that Microsoft provides as examples when the custom.ts file opens.

**Comment by maddie4832** [comment]
Success! Thank you!

**Comment by compie67** [comment]
202o stil not found in the extensions.
Any workable workaround to provide to my students. Age 14 to 17 years old
Got the microbit, GPIO board and the CSS811 sensor
Thanks in advanged
